import React, { useState } from 'react';
import { AnalysisResult, AnalysisType, ResearchReportData, MoleculeAnalysisData, TextAnalysisData, ComparisonData } from '../types';
import { generateResearchReport } from '../services/geminiService';
import { Download, FileBarChart, Clock, Database, ChevronRight, Sparkles, Loader2, FileText, AlertTriangle, X, Eye, Tag, Layers, Microscope } from 'lucide-react';

interface Props {
  history: AnalysisResult[];
}

const getDomainColor = (domain: string = 'General') => {
    const lower = domain.toLowerCase();
    if (lower.includes('pharma') || lower.includes('bio')) return 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30';
    if (lower.includes('chem') || lower.includes('organic')) return 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30';
    if (lower.includes('material') || lower.includes('physics')) return 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30';
    return 'bg-slate-700/50 text-slate-300 border-slate-600/50';
};

const ReportView: React.FC<Props> = ({ history }) => {
  const [loading, setLoading] = useState(false);
  const [reportData, setReportData] = useState<ResearchReportData | null>(null);
  const [selectedSession, setSelectedSession] = useState<AnalysisResult | null>(null);

  const handleDownloadJSON = () => {
    const reportText = JSON.stringify(history, null, 2);
    const blob = new Blob([reportText], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `NovaSynth_Data_Export_${new Date().toISOString().split('T')[0]}.json`;
    a.click();
  };

  const handleGenerateReport = async () => {
    if (history.length === 0) return;
    setLoading(true);
    try {
        const data = await generateResearchReport(history);
        setReportData(data);
    } catch (error) {
        console.error("Report generation failed", error);
    } finally {
        setLoading(false);
    }
  };

  const handleDownloadTxt = () => {
    if (!reportData) return;
    
    let textContent = `NOVA SYNTH AI - RESEARCH INSIGHT REPORT\nDate: ${new Date().toLocaleString()}\n\n`;
    
    reportData.reports.forEach((rep, idx) => {
        textContent += `\n========================================\n`;
        textContent += `DOMAIN ${idx + 1}: ${rep.domainName.toUpperCase()}\n`;
        textContent += `TITLE: ${rep.title}\n`;
        textContent += `========================================\n\n`;
        textContent += `1. INTRODUCTION\n${rep.introduction}\n\n`;
        textContent += `2. METHOD & INPUTS\n${rep.methodInputs}\n\n`;
        textContent += `3. KEY INSIGHTS\n${rep.keyInsights}\n\n`;
        textContent += `4. SUGGESTED VARIATIONS\n${rep.suggestedVariations}\n\n`;
        textContent += `5. LIMITATIONS\n${rep.limitations}\n\n`;
        textContent += `6. SUMMARY\n${rep.domainSummary}\n\n`;
    });

    textContent += `\n----------------------------------------\n`;
    textContent += `GLOBAL SAFETY NOTICE\n${reportData.globalSafetyNotice}\n`;
    textContent += `\nGenerated by Gemini 3 Pro via NovaSynth AI`;

    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `NovaSynth_MultiDomain_Report_${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
  };

  const renderModalContent = (session: AnalysisResult) => {
      if (session.type === AnalysisType.IMAGE) {
          const d = session.data as MoleculeAnalysisData;
          return (
              <div className="space-y-6">
                  <div className="grid grid-cols-2 gap-4">
                      <div className="bg-slate-800/50 p-4 rounded-xl border border-slate-700">
                          <h6 className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Formula</h6>
                          <p className="text-white font-mono">{d.formula || 'N/A'}</p>
                      </div>
                      <div className="bg-slate-800/50 p-4 rounded-xl border border-slate-700">
                          <h6 className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Domain</h6>
                          <p className="text-cyan-400 font-bold">{d.domain || 'General'}</p>
                      </div>
                  </div>
                  <div>
                      <h6 className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-2">Key Properties</h6>
                      <ul className="space-y-2 text-sm text-slate-300">
                          <li><span className="text-slate-500">Solubility:</span> {d.properties.solubility}</li>
                          <li><span className="text-slate-500">Stability:</span> {d.properties.stability}</li>
                      </ul>
                  </div>
                  <div>
                      <h6 className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-2">Analysis Summary</h6>
                      <p className="text-sm text-slate-300 leading-relaxed bg-slate-950/30 p-4 rounded-lg border border-slate-800/50">{d.rawAnalysis}</p>
                  </div>
              </div>
          );
      } else if (session.type === AnalysisType.TEXT) {
          const d = session.data as TextAnalysisData;
          return (
              <div className="space-y-6">
                  <div className="grid grid-cols-2 gap-4">
                      <div className="bg-slate-800/50 p-4 rounded-xl border border-slate-700">
                          <h6 className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Type</h6>
                          <p className="text-white font-mono">{d.experimentType || 'N/A'}</p>
                      </div>
                      <div className="bg-slate-800/50 p-4 rounded-xl border border-slate-700">
                           <h6 className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Domain</h6>
                           <p className="text-indigo-400 font-bold">{d.domain || 'Research'}</p>
                      </div>
                  </div>
                  <div>
                      <h6 className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-2">Key Concepts</h6>
                      <div className="flex flex-wrap gap-2">
                          {d.keyConcepts?.slice(0,6).map((c, i) => (
                              <span key={i} className="px-2 py-1 bg-slate-900 border border-slate-700 rounded text-xs text-slate-400">#{c}</span>
                          ))}
                      </div>
                  </div>
                  <div>
                      <h6 className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-2">Executive Summary</h6>
                      <p className="text-sm text-slate-300 leading-relaxed bg-slate-950/30 p-4 rounded-lg border border-slate-800/50">{d.summary}</p>
                  </div>
              </div>
          );
      } else if (session.type === AnalysisType.COMPARISON) {
          const d = session.data as ComparisonData;
          return (
              <div className="space-y-6">
                   <div className="flex items-center justify-between bg-slate-800/50 p-4 rounded-xl border border-slate-700">
                        <div>
                             <h6 className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Comparison</h6>
                             <p className="text-white font-bold">{d.molecule1} <span className="text-slate-500 mx-2">vs</span> {d.molecule2}</p>
                        </div>
                        <div className="text-right">
                             <h6 className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-1">Score</h6>
                             <p className="text-purple-400 font-mono text-xl">{d.similarityScore}%</p>
                        </div>
                   </div>
                   <div>
                        <h6 className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-2">Reasoning</h6>
                        <ul className="space-y-2">
                             {d.reasoningSnapshot?.map((r, i) => (
                                 <li key={i} className="text-sm text-slate-300 flex items-start gap-2">
                                     <span className="w-1.5 h-1.5 rounded-full bg-purple-500 mt-1.5 shrink-0"></span>
                                     {r}
                                 </li>
                             ))}
                        </ul>
                   </div>
                   <div>
                        <h6 className="text-[10px] text-slate-500 uppercase tracking-widest font-bold mb-2">Summary</h6>
                        <p className="text-sm text-slate-300 leading-relaxed bg-slate-950/30 p-4 rounded-lg border border-slate-800/50">{d.similarityExplanation}</p>
                   </div>
              </div>
          );
      }
      return <p className="text-slate-500">No data available.</p>;
  };

  return (
    <div className="space-y-8 animate-fade-in pb-10 relative">
      {/* Detail Modal */}
      {selectedSession && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
             <div className="absolute inset-0 bg-slate-950/90 backdrop-blur-sm transition-opacity" onClick={() => setSelectedSession(null)}></div>
             <div className="bg-slate-900 border border-slate-700 rounded-3xl w-full max-w-2xl max-h-[85vh] overflow-hidden flex flex-col shadow-2xl relative z-10 animate-fade-in-up">
                  <div className="p-6 border-b border-slate-800 flex justify-between items-center bg-slate-950/50">
                      <div className="flex items-center gap-4">
                          <div className={`p-2.5 rounded-xl ${
                              selectedSession.type === AnalysisType.IMAGE ? 'bg-cyan-500/10 text-cyan-400' :
                              selectedSession.type === AnalysisType.TEXT ? 'bg-indigo-500/10 text-indigo-400' : 'bg-purple-500/10 text-purple-400'
                          }`}>
                              {selectedSession.type === AnalysisType.IMAGE ? <Microscope className="w-5 h-5"/> : 
                               selectedSession.type === AnalysisType.TEXT ? <FileText className="w-5 h-5"/> : <Layers className="w-5 h-5"/>}
                          </div>
                          <div>
                              <h4 className="text-lg font-bold text-white mb-0.5">{selectedSession.title}</h4>
                              <p className="text-slate-500 text-xs font-mono">
                                  {new Date(selectedSession.timestamp).toLocaleString()}
                              </p>
                          </div>
                      </div>
                      <button 
                        onClick={() => setSelectedSession(null)}
                        className="p-2 rounded-full hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
                      >
                          <X className="w-5 h-5" />
                      </button>
                  </div>
                  <div className="p-8 overflow-y-auto custom-scrollbar bg-slate-900">
                      {renderModalContent(selectedSession)}
                  </div>
             </div>
        </div>
      )}

      {/* Main Header */}
      <div className="flex flex-col md:flex-row justify-between items-end gap-4 border-b border-slate-800/60 pb-8">
        <div>
             <div className="flex items-center gap-2 mb-3">
                <span className="px-2.5 py-1 rounded text-[10px] font-bold bg-slate-700/50 text-slate-300 border border-slate-600/50 uppercase tracking-wider">
                    Data Aggregation
                </span>
            </div>
            <h2 className="text-4xl font-bold text-white tracking-tight font-sans">Research Summary</h2>
            <p className="text-slate-400 mt-3 max-w-2xl text-lg font-light">Compile your session insights into structured, domain-specific research reports.</p>
        </div>
        <div className="flex gap-3">
            <button 
                onClick={handleGenerateReport}
                disabled={history.length === 0 || loading}
                className={`
                    px-6 py-4 rounded-xl text-sm font-bold uppercase tracking-wide flex items-center gap-2 transition-all
                    ${history.length === 0 || loading 
                        ? 'bg-slate-800 text-slate-600 cursor-not-allowed' 
                        : 'bg-scifi-accent text-slate-900 hover:bg-cyan-400 shadow-[0_0_20px_rgba(6,182,212,0.3)] hover:translate-y-[-2px]'
                    }
                `}
            >
                {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
                {loading ? 'Analyzing Domains...' : 'Generate Report'}
            </button>

            <button 
                onClick={handleDownloadJSON}
                disabled={history.length === 0}
                className="bg-slate-800 text-slate-200 border border-slate-700 px-6 py-4 rounded-xl text-sm font-bold uppercase tracking-wide flex items-center gap-2 transition-all hover:bg-slate-700 hover:text-white"
            >
                <Download className="w-4 h-4" /> Export Data
            </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Column: History List */}
        <div className="lg:col-span-8 space-y-6">
            {history.length === 0 ? (
                <div className="p-20 border-2 border-dashed border-slate-800 rounded-3xl flex flex-col items-center justify-center text-slate-600 bg-slate-900/20">
                    <Database className="w-16 h-16 mb-6 opacity-20" />
                    <p className="text-lg">No analysis data generated yet.</p>
                </div>
            ) : (
                <div className="space-y-4">
                    <h3 className="text-[10px] font-bold text-slate-500 uppercase tracking-widest ml-1 flex items-center gap-2">
                        <Database className="w-3 h-3" /> Session Data Sources
                    </h3>
                    <div className="grid grid-cols-1 gap-3">
                        {history.map((item) => {
                            // Extract domain tag if available, else default
                            const domainTag = item.data?.domain || (item.type === AnalysisType.COMPARISON ? 'Comparative Study' : 'General Research');
                            
                            return (
                                <div 
                                    key={item.id} 
                                    onClick={() => setSelectedSession(item)}
                                    className="glass-panel p-5 rounded-xl border-l-4 border-l-slate-700/50 flex justify-between items-center group hover:bg-slate-800/60 hover:scale-[1.01] hover:border-l-scifi-accent transition-all cursor-pointer shadow-sm hover:shadow-lg"
                                >
                                    <div>
                                        <div className="flex items-center gap-3 mb-2">
                                            <span className={`text-[9px] font-bold px-2 py-0.5 rounded border uppercase tracking-wider ${getDomainColor(domainTag)}`}>
                                                {domainTag}
                                            </span>
                                            <span className="text-slate-500 text-[10px] flex items-center gap-1 font-mono">
                                                <Clock className="w-3 h-3" />
                                                {new Date(item.timestamp).toLocaleTimeString()}
                                            </span>
                                        </div>
                                        <h4 className="font-bold text-slate-300 text-sm truncate max-w-md group-hover:text-white transition-colors">
                                            {item.title}
                                        </h4>
                                    </div>
                                    <div className="flex items-center gap-3 opacity-0 group-hover:opacity-100 transition-opacity">
                                        <span className="text-[10px] font-bold uppercase tracking-wider text-scifi-accent">View Data</span>
                                        <div className="p-1.5 rounded-full bg-slate-800 text-scifi-accent border border-slate-700">
                                            <ChevronRight className="w-4 h-4" />
                                        </div>
                                    </div>
                                </div>
                            );
                        })}
                    </div>
                </div>
            )}
            
            {/* Generated Report Section - Multi-Domain */}
            {reportData && (
                <div className="mt-12 animate-fade-in-up">
                    <div className="flex items-center justify-between mb-6">
                        <h3 className="text-2xl font-bold text-white flex items-center gap-3">
                            <FileText className="w-6 h-6 text-scifi-accent" />
                            Generated Research Reports
                        </h3>
                        <button 
                             onClick={handleDownloadTxt}
                             className="text-xs font-bold uppercase tracking-wider text-scifi-accent hover:text-white flex items-center gap-2 transition-colors"
                        >
                            <Download className="w-3 h-3" /> Download Full .TXT
                        </button>
                    </div>

                    <div className="space-y-8">
                        {reportData.reports.map((report, idx) => (
                            <div key={idx} className="glass-panel p-8 rounded-3xl border border-scifi-accent/20 bg-slate-900/80 backdrop-blur-xl relative overflow-hidden">
                                {/* Domain Header */}
                                <div className="border-b border-slate-800 pb-6 mb-6">
                                    <div className="flex items-center gap-3 mb-3">
                                        <span className={`px-3 py-1 rounded text-xs font-bold uppercase tracking-widest border ${getDomainColor(report.domainName)}`}>
                                            Domain {idx + 1}: {report.domainName}
                                        </span>
                                    </div>
                                    <h4 className="text-2xl font-bold text-white">{report.title}</h4>
                                </div>

                                <div className="space-y-8 font-light text-slate-300">
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                        <div>
                                            <h5 className="text-xs font-bold text-scifi-accent uppercase tracking-widest mb-3">1. Introduction</h5>
                                            <div className="text-sm leading-relaxed text-slate-300 whitespace-pre-line">{report.introduction}</div>
                                        </div>
                                        <div>
                                            <h5 className="text-xs font-bold text-scifi-accent uppercase tracking-widest mb-3">2. Methods & Inputs</h5>
                                            <div className="text-sm leading-relaxed text-slate-300 whitespace-pre-line">{report.methodInputs}</div>
                                        </div>
                                    </div>

                                    <div className="bg-slate-800/30 p-6 rounded-xl border border-slate-800">
                                        <h5 className="text-xs font-bold text-scifi-accent uppercase tracking-widest mb-3">3. Key Insights</h5>
                                        <div className="text-base leading-relaxed text-white whitespace-pre-line">{report.keyInsights}</div>
                                    </div>

                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                        <div>
                                            <h5 className="text-xs font-bold text-scifi-accent uppercase tracking-widest mb-3">4. Suggested Variations</h5>
                                            <div className="text-sm leading-relaxed text-slate-300 whitespace-pre-line">{report.suggestedVariations}</div>
                                        </div>
                                        <div>
                                            <h5 className="text-xs font-bold text-scifi-accent uppercase tracking-widest mb-3">5. Limitations</h5>
                                            <div className="text-sm leading-relaxed text-slate-300 whitespace-pre-line">{report.limitations}</div>
                                        </div>
                                    </div>

                                    <div className="bg-gradient-to-r from-slate-900 to-slate-800 p-6 rounded-xl border border-slate-700/50">
                                        <h5 className="text-xs font-bold text-scifi-accent uppercase tracking-widest mb-3">6. Domain Summary</h5>
                                        <div className="text-sm leading-relaxed text-slate-200 whitespace-pre-line">{report.domainSummary}</div>
                                    </div>
                                </div>
                            </div>
                        ))}

                        {/* Global Safety */}
                        <div className="pt-6 border-t border-slate-800/50 flex items-start justify-center gap-3">
                            <AlertTriangle className="w-5 h-5 text-yellow-500 shrink-0" />
                            <div className="max-w-2xl text-center md:text-left">
                                <h5 className="text-[10px] font-bold text-yellow-500 uppercase tracking-widest mb-1">Global Safety Notice</h5>
                                <p className="text-xs text-yellow-500/80 leading-relaxed">{reportData.globalSafetyNotice}</p>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>

        {/* Right Column: Stats */}
        <div className="lg:col-span-4 space-y-6">
            <div className="bg-gradient-to-br from-slate-900 to-slate-950 p-8 rounded-3xl border border-slate-800 shadow-xl sticky top-6">
                <FileBarChart className="w-12 h-12 text-scifi-accent mb-6" />
                <h3 className="text-2xl font-bold text-white mb-2">Insight Summary</h3>
                <div className="space-y-4 mt-8">
                    <div className="flex justify-between items-center text-sm border-b border-slate-800 pb-4">
                        <span className="text-slate-400 font-medium">Total Analyses</span>
                        <span className="text-white font-mono text-xl">{history.length}</span>
                    </div>
                    {/* Dynamic Domain Counter */}
                    <div className="bg-slate-800/40 rounded-xl p-4 space-y-3">
                        <h5 className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Active Domains</h5>
                        <div className="flex flex-wrap gap-2">
                             {Array.from(new Set(history.map(h => h.data?.domain || 'General'))).map((d, i) => (
                                 <span key={i} className={`text-[10px] px-2 py-1 rounded border uppercase ${getDomainColor(d)}`}>
                                     {d}
                                 </span>
                             ))}
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  );
};

export default ReportView;